[tool.poetry]
name = "robosubcv"
version = "0.1.0"
description = "Robosub Computer Vision repo for Capstone"
authors = ["Kye Buerkle <22kyebue@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
opencv-python = "^4.13.0.90"
pandas = "^3.0.0"
roboflow = "^1.2.13"
ultralytics = "^8.4.8"
torch = { version = "*", optional = true }
torchvision = { version = "*", optional = true }
torchaudio = { version = "*", optional = true }
pytest = "^9.0.2"
argparse = "^1.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
testpaths = ["src"]
pythonpath = ["src"]
addopts = """
    --ignore=src/roboflow_datasets/tests/test_coco_download.py
    --ignore=src/roboflow_datasets/tests/test_yolo_download.py
"""