[tool.poetry]
name = "robosubcv"
version = "1.1.2"
description = "Robosub Computer Vision repo for Capstone"
authors = ["Kye Buerkle <22kyebue@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "roboflow_datasets", from = "src"}, 
            {include = "general_lib", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
opencv-python = "^4.13.0.90"
pandas = "^3.0.0"
roboflow = "^1.2.13"
pytest = "^9.0.2"
argparse = "^1.4.0"
# this script needs ultralytics

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["src"]
pythonpath = ["src"]
addopts = """
    --ignore=src/roboflow_datasets/tests/test_coco_download.py
    --ignore=src/roboflow_datasets/tests/test_yolo_download.py
    --ignore=src/model_training/tests/test_evaluate_yolo.py
"""
asset_dir = "assets/test-images"
