[tool.poetry]
name = "robosubcv"
version = "0.1.0"
description = "Robosub Computer Vision repo for Capstone"
authors = ["Kye Buerkle <22kyebue@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
opencv-python = "^4.13.0.90"
pandas = "^3.0.0"
roboflow = "^1.2.13"
ultralytics = "^8.4.8"
torch = { version = "*", optional = true }
torchvision = { version = "*", optional = true }
torchaudio = { version = "*", optional = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
